<!-- BUTTON -->
<?php $btnSave    = $this->cmsButtonToolbar('Lưu', 'fa-save', 'save', null, null);?>

<?php echo $this->render('area_toolbar-customer.phtml'); ?>
<!-- NOTICE -->
<?php echo $this->flashMessenger()->render(); ?>
<?php echo $this->myForm->showMessage(); ?>

<div class="box box-info">
    <div class="box-body">
		<?php
			$myForm = $this->myForm;
			$myForm->prepare();
			echo $this->form()->openTag($myForm);
			echo $this->partialLoop('form_row.phtml', array(
				array('elm' => $myForm->get('time')),
				array('elm' => $myForm->get('id'), 'type' => 'hidden'),
			));
			echo $this->form()->closeTag();
		?>
    </div>
    <div class="row">
        <div class="text-center">
			<?php echo $btnSave; ?>
        </div>
    </div>
</div>
