<?php echo $this->doctype();?>
<html>
	<head>
		<?php 
			// Title
			echo $this->headTitle()->append('Frontend');
			
			// Meta
			echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')
								  ->appendName('description', 'ZendVN - Zend framework 2.x')
								  ->setCharset('utf-8');
		?>
	</head>
	<body>
		<div class="container">
			<?php echo $this->content; ?>
		</div>
	</body>
</html>