<?php
	// DATA ITEM
	$xhtmlItems = '';
	if (!empty($this->items)) {
		foreach ($this->items as $item) {
			$class       = $this->cycle(array('odd', 'even'))->next();
			$id          = $item->id;
			$name        = $item->name;
			$week        = $item->week;
			$time        = date('d-m-Y', strtotime($item->time));
			$created     = date('H:i:s d-m-Y', strtotime($item->created));
			$createdBy   = $item->created_by;
			$description = $item->description;
			$status      = $item->status == 1 ? "Đang mở" : "Đã đóng";
			$linkEdit    = $this->cmsLinkCustomer(array('controller' => 'timeline', 'action' => 'submission', 'id' => $id));
			$xhtmlItems  .= '<tr class="' . $class . '">
								<td><a href="' . $linkEdit . '">' . $name . '</a></td>
								<td>' . $week . '</td>
								<td>' . $time . '</td>
								<td>' . $description . '</td>
								<td>' . $created . '</td>
								<td>' . $createdBy . '</td>
								<td>' . $status . '</td>
							</tr>';
		}
	}
?>

<!-- NOTICE -->
<?php echo $this->flashMessenger()->render(); ?>

<div class="box box-info">
    <div class="box-body table-responsive">
        <div class="dataTables_wrapper" role="grid">
            <table class="table table-bordered table-striped dataTable text-center">
                <!-- COLUMN TITLE -->
                <thead>
                <tr role="row">
                    <th>Tên giáo án</th>
                    <th>Số tuần</th>
                    <th>Thời gian bắt đầu</th>
                    <th>Yêu cầu</th>
                    <th>Tạo vào ngày</th>
                    <th>Tạo bởi</th>
                    <th>Trạng thái</th>
                </tr>
                </thead>

                <!-- CONTENT TABLE -->
                <tbody><?php echo $xhtmlItems; ?></tbody>
            </table>

            <!-- PAGINATION -->
			<?php
				$currentURL = $this->cmsLinkCustomer(array('controller' => 'timeline', 'action' => 'submission'));
				echo $this->paginationControl($this->paginator, 'sliding', 'paginator.phtml', array('currentURL' => $currentURL));
			?>
        </div>
        </form>
    </div>