<?php
	//$name, $icon, $type, $showTotal = null, $link = null
	$currentController = $this->layout()->controller;
	$currentAction     = $this->layout()->action;
	
	switch ($currentAction){
		case 'index':
			$linkAdd   = $this->cmsLinkCustomer(array('controller' => $currentController, 'action' => 'form'));
			$btnAdd    = $this->cmsButtonToolbar('Nộp bài', 'fa-plus-square-o', null, null, $linkAdd);
			$btnDelete = $this->cmsButtonToolbar('Xóa bài', 'fa-minus-square-o', 'delete', 'yes', null);
			
			$strToolbar = $btnAdd . $btnDelete;
			
			break;
		
		case 'form':
			$btnSave    = $this->cmsButtonToolbar('Nộp bài', 'fa-save', 'save', null, null);
			$linkCancel = $this->cmsLinkCustomer(array('controller' => $currentController, 'action' => 'submission', "id" => $this->id_homework));
			$btnCancel  = $this->cmsButtonToolbar('Trở về', 'fa-arrow-circle-left', null, null, $linkCancel);
			$strToolbar = $btnSave . $btnCancel;
			break;
		
		default:
			break;
	}
?>
<div class="row">
    <div class="text-center">
		<?php echo $strToolbar; ?>
    </div>
</div>